pygments:       true
lsi:            false
paginate:       5
permalink:      /:year/:month/:day/:title/
excerpt_separator: "\n\n"

exclude: 
    - README.md
    - Rakefile
    - artwork
    - Gemfile
    - Gemfile.lock
    - wolfeidau_site.iml
    - vendor
    - bin

title:          wolfeidau
description:    "Observations and musings of Mark Wolfe, a builder of internet related things."

author:
    name:       Mark Wolfe
    email:      mark.wolfe@hsd.com.au
    twitter:    wolfeidau

keywords:
    - Development
    - Internet
    - Unix
    - Cryptography

disqus:
    id:         markwolfesblog

nav:
    - name: Weblog
      url:  /

    - name: About
      url: /about/


copyright: "&copy; Copyright 2013, Mark Wolfe.<br> All Rights Reserved."
